version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: finances-postgres
    hostname: postgres
    restart: unless-stopped
    ports:
      - 5432:5432    
    env_file:
      - ./server/.env
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: finances-pgadmin
    restart: unless-stopped
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres

  node-server:    
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: finances-server    
    restart: always
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules 
    env_file:
      - ./server/.env    
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres-data:
  pgadmin-data:
